CREATE DATABASE ChamaJussaBD;
GO

USE ChamaJussaBD
GO

CREATE TABLE OrdemServico(
    IdOS UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Titulo NVARCHAR(100) NOT NULL,
	Equipamento NVARCHAR(100) NOT NULL,
	[Local] NVARCHAR(100) NOT NULL,
	Descricao NVARCHAR(MAX) NOT NULL,
	Imagem VARCHAR(100) NOT NULL,
	[Status] NVARCHAR(20) NOT NULL DEFAULT 'Aberto',
);
GO

CREATE TABLE Usuario(
    IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Nome VARCHAR(100) NOT NULL,
	Senha VARCHAR(60) NOT NULL,
	Email VARCHAR(256) NOT NULL UNIQUE,
	TipoUsuario VARCHAR(20) NOT NULL DEFAULT 'Comum',
	Imagem VARCHAR(100) NOT NULL,
	);
GO

SELECT * FROM Usuario;
SELECT * FROM OrdemServico;